### ISSUE TITLE
Unhandled exception is config settings are null

### ISSUE THREAD

**Issue by itsmemattchung** [kkamkou/node-akamai-http-api#7]
We are using `process.env.AKAMAI_KEY_NAME`, `process.env.KEY`, `process.env.AKAMAI_HOSTNAME` to initialize `setConfig()`.  If setConfig is passed `null` values and `dir` (or any other akamai calls) is called, an unhanded exception is raised.  @kkamkou , what are your thoughts about detecting an empty configuration? 

```Javascript
var akamai = require('akamai-http-api');

akamai.dir('/', function(err, data){
  console.log(data);
})
```

`vagrant@vagrant-ubuntu-trusty-64:/vagrant$ node akamai_test.js `

```Javascript
crypto.js:257
  this._binding.init(hmac, toBuf(key));
                ^
TypeError: Not a buffer
    at new Hmac (crypto.js:257:17)
    at Object.Hmac (crypto.js:255:12)
    at akamai.getHeaders (/vagrant/node_modules/akamai-http-api/lib/akamai.js:83:21)
    at akamai.getRequestObject (/vagrant/node_modules/akamai-http-api/lib/akamai.js:144:46)
    at akamai.dir (/vagrant/node_modules/akamai-http-api/lib/akamai.js:217:8)
    at Object.<anonymous> (/vagrant/akamai_test.js:3:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

**Comment by kkamkou** [comment]
Nice catch. I see here two options:
- add an [assert](https://nodejs.org/api/assert.html) check to function.
- keep it as-is. Because a developer should configure the object anyway.

Personally I prefer the second variant. Because it is not up to the obejct. You can extend it and modify the `setConfig` to accept an alias(or use the `process.env.AKAMAI_KEY_NAME`). Please, share you opinion if any.

**Comment by itsmemattchung** [comment]
Ok thanks @kkamkou .  Thanks for the library again. Working out well in our solution.
